# -*- coding: utf-8 -*-
"""convertidor pdf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kl-6sga7sDBrDNODxRsfj_p0rRKCoUms
"""

# ============================================
# PROGRAMA CON INTERFAZ PARA UNIR PDFs EN COLAB
# ============================================

# 1. Instalamos la librería necesaria
!pip install PyPDF2 -q

# 2. Importamos las herramientas
from google.colab import files
from PyPDF2 import PdfMerger
import ipywidgets as widgets
from IPython.display import display, clear_output

# 3. Variables globales
archivos_pdf = []

# 4. Zona de mensajes
salida = widgets.Output()

# 5. Botón para subir PDFs
boton_subir = widgets.Button(
    description=" Subir PDFs",
    button_style="info"
)

# 6. Lista visual para mostrar los PDFs subidos
lista_archivos = widgets.SelectMultiple(
    options=[],
    description="PDFs:",
    rows=8,
    layout=widgets.Layout(width="500px")
)

# 7. Campo para escribir el nombre del PDF final
nombre_salida = widgets.Text(
    value="PDF_unido.pdf",
    description="Salida:",
    layout=widgets.Layout(width="500px")
)

# 8. Botón para unir los PDFs
boton_unir = widgets.Button(
    description=" Unir PDFs",
    button_style="success"
)

# 9. Botón para descargar
boton_descargar = widgets.Button(
    description=" Descargar PDF",
    button_style="warning",
    disabled=True
)

# 10. Función para subir PDFs
def subir_pdfs(b):
    global archivos_pdf

    with salida:
        clear_output()
        print("Selecciona tus archivos PDF...")

    uploaded = files.upload()

    for nombre in uploaded.keys():
        if nombre.lower().endswith(".pdf"):
            archivos_pdf.append(nombre)

    lista_archivos.options = archivos_pdf

    with salida:
        clear_output()
        print("PDFs subidos correctamente:")
        for pdf in archivos_pdf:
            print("•", pdf)

# 11. Función para unir PDFs
def unir_pdfs(b):
    with salida:
        clear_output()

        if len(archivos_pdf) < 2:
            print("Debes subir al menos 2 archivos PDF.")
            return

        merger = PdfMerger()

        print("Uniendo archivos en este orden:")

        for pdf in archivos_pdf:
            print("•", pdf)
            merger.append(pdf)

        merger.write(nombre_salida.value)
        merger.close()

        boton_descargar.disabled = False

        print("\nPDF creado correctamente:", nombre_salida.value)

# 12. Función para descargar el PDF final
def descargar_pdf(b):
    files.download(nombre_salida.value)

# 13. Conectar botones con funciones
boton_subir.on_click(subir_pdfs)
boton_unir.on_click(unir_pdfs)
boton_descargar.on_click(descargar_pdf)

# 14. Mostrar interfaz
titulo = widgets.HTML("""
<h2> Unidor de PDFs en Google Colab</h2>
<p>Sube varios archivos PDF, únelos y descarga un único documento final.</p>
""")

display(titulo)
display(boton_subir)
display(lista_archivos)
display(nombre_salida)
display(widgets.HBox([boton_unir, boton_descargar]))
display(salida)